### ISSUE TITLE
sick-nano driver  occured segfault

### ISSUE THREAD

**Issue by menggtgt** [SICKAG/sick_safetyscanners#59] opened 2020-09-04 01:11 UTC
The driver program has an error as shown in the figure, and it died, please help me to solve this problem
![sefety_scaner_segfault](https://user-images.githubusercontent.com/52225221/92187937-be604100-ee8d-11ea-9eae-b488eb6c3980.png)

**Comment by menggtgt** [comment] 2020-09-04 01:16
Picture may be blurry.

sick_safetyscan[2639]: segfault at 7fB09B03b001 ip 00007fB0b2c3094e sp 00007f80aa29a390 error 4 in libsick_safetyscanners_core.so[7f80b2a26000+29a000]

**Comment by puck-fzi** [comment] 2020-09-04 06:10
Hi, i am currently not in the Office. Could you maybe Check If the fix_check_measurementdata_length branch does solve this Problem?

If Not a Stacktrace would be appreciated. Since i cannot reproduce the Error. Preferably in a debug build. Thanks

**Comment by menggtgt** [comment] 2020-09-04 08:56
No problem. I will try to get a stack trace and/or try the mentioned branch.  I will keep you updated using this issue. Thanks

**Comment by menggtgt** [comment] 2020-09-07 09:04
Hi, The error appeared again, and the results of debugging with GDB are as follows:

![error](https://user-images.githubusercontent.com/52225221/92369854-1f0ca980-f12c-11ea-9cdc-23bac846b62e.png)

Thread 6 "sick_safetyscan" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeaffd700 (LWP 6018)]
0x00007ffff7b3494e in sick::read_write_helper::readUint16LittleEndian (it=0 '\000')
    at /sick_safetyscanners/include/sick_safetyscanners/data_processing/ReadWriteHelper.hpp:276
276	  return (*(it + 1) << 8) + *(it + 0);
(gdb) quit
A debugging session is active.

	Inferior 1 [process 4871] will be killed.

Quit anyway? (y or n) [answered Y; input not from terminal]
================================================================================REQUIRED process [front/sick_safetyscanners-5] has died!
process has finished cleanly
log file: .ros/log/52ddbb94-f0e3-11ea-b809-c400ad2cc288/front-sick_safetyscanners-5*.log
Initiating shutdown!
================================================================================

**Comment by puck-fzi** [comment] 2020-09-07 11:35
Hi, did you use the suggested Branch? And a Stack trace using gdb would be helpful. As it appears there is a read request of a 16bit field which is Out of range. Could you Provide the Stack trace using `backtrace` or `bt` in gdb once the Driver Crashes. Thank you

**Comment by puck-fzi** [comment] 2020-09-08 13:04
possible duplicate of https://github.com/SICKAG/sick_safetyscanners/issues/58

**Comment by menggtgt** [comment] 2020-09-08 13:21
Thank you very much, the suggested branch seems to solve this problem and there is no crash yet. Need to verify a few days

**Comment by puck-fzi** [comment] 2020-09-08 13:23
Glad to hear, please let me know if that fixes it for you in the long term, then i will integrate this branch into the master and trigger a new release.

**Comment by puck-fzi** [comment] 2020-09-14 11:03
Does the branch fix the proplem? If yes i will merge it into the master

**Comment by menggtgt** [comment] 2020-09-14 12:14
yes, the error did not reappear

**Closed** 2020-09-14 12:15 UTC

**Comment by puck-fzi** [comment] 2020-09-14 18:58
Glad to Hear. Then i will merge the branch.
