### ISSUE TITLE
 Abnormal radar data publishing problems during operation

### ISSUE THREAD

**Issue by 0n1whq** [SICKAG/sick_safetyscanners#116] opened 2023-02-17 09:15 UTC
The latest version 1.0.8 driver occasionally has abnormal radar data publishing problems during operation, which can be restored to normal after restarting the node, seriously affecting the operation. The specific analysis of the problem is as follows: 1. Check that the physical network connection between the host and the sensor is normal; 2. Use the Wireshark network analysis tool to monitor the data transmission between the host and the sensor. The packet length is normal and the transmission is normal; 3. Print the topic scan data of the node without information; 4. Restart the node to recover. The preliminary judgment is that it is a driving problem. Please check and improve it as soon as possible. Thanks!

**Comment by puck-fzi** [comment] 2023-02-21 08:33
closing since its a duplicate of #117

**Closed by puck-fzi** 2023-02-21 08:33 UTC
