### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by reinzor** [SICKAG/sick_safetyscanners#58] opened 2020-08-31 12:11 UTC
Version: `1.0.5`

```
terminate called after throwing an instance of 'std::out_of_range'
what():  vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 0)
```

Follow up of #32 

Bug still seems to be present in the latest version

**Comment by puck-fzi** [comment] 2020-09-04 06:08
Hi, am still Not in the Office. Could you maybe Check If the fix_check_measurementdata_length branch does solve this Problem?

If Not i Stack trace would be appriciated. Since i cannot reproduce the Error.

**Comment by reinzor** [comment] 2020-09-04 06:43
No problem. I will try to get a stack trace and/or try the mentioned branch. Problem is really hard to reproduce since it only happens once per week or maybe less. I will keep you updated using this issue.

**Comment by puck-fzi** [comment] 2020-09-14 11:04
Does the branch fix the problem? If yes, i will merge it into the master

**Comment by reinzor** [comment] 2020-09-14 11:10
We have not experienced this issue yet. But it does not occur often so I cannot really validate that the problem is fixed yet.

**Comment by puck-fzi** [comment] 2020-09-14 11:15
Thanks, i'll might ping in a week again, to see if this is resolved. Thanks for letting me know

**Comment by puck-fzi** [comment] 2020-09-21 08:41
I merged the branch into the master. If the issue still persists please reopen

**Closed by puck-fzi** 2020-09-21 08:41 UTC

**Comment by akifh** [comment] 2021-05-05 05:47
@puck-fzi It is still present with `1.0.8`

```
May 04 22:28:43: terminate called after throwing an instance of 'std::out_of_range'
May 04 22:28:43:   what():  vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 0)
```

**Comment by puck-fzi** [comment] 2021-05-05 06:19
Hi could you build the library in debug mode and provide me with a stacktrace. So I can see where the error occurs.
So far I did not experience the error again. Thanks
